version: '3.4'
services:
  db:
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: a123321475
      MYSQL_USER: root
      MYSQL_PASSWORD: a123321475
      MYSQL_DATABASE: MeuBlog
    ports:
      - "3308:3306"
    networks:
      - generation-network
  meublog-api:
    restart: always
    build: ./MeuBlog
    working_dir: /MeuBlog
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
     - ./MeuBlog:/MeuBlog
     - ~/.m2:/root/.m2
    ports:
      - "9000:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - generation-network
      
    networks:
    - generation-network 
networks: 
    generation-network:
      driver: bridge 